esphome:
    on_boot: 
      then:
        - lambda: |-
            if (id(battery_last_replaced_global) != 0)
            {
              id(battery_last_replaced_sensor).publish_state(id(battery_last_replaced_global));
            }
            if (${battery_notes_count} == 1)
            {
                id(battery_type_text).publish_state("${battery_notes_type}");
            }
            else
            {
                id(battery_type_text).publish_state("${battery_notes_count}× ${battery_notes_type}");
            }

globals:
  - id: battery_last_replaced_global
    type: time_t
    restore_value: true

button:
  - platform: template
    id: battery_replaced_button
    name: "Battery replaced"
    entity_category: diagnostic
    on_press: 
      then:
        - lambda: |-
            auto nowTime = id(${battery_notes_time_id}).now();
            if (nowTime.is_valid())
            {
                id(battery_last_replaced_global) = nowTime.timestamp;
                id(battery_last_replaced_sensor).publish_state(id(battery_last_replaced_global));
            }

sensor:
  - platform: template
    id: battery_last_replaced_sensor
    name: "Battery last replaced"
    entity_category: diagnostic
    device_class: timestamp
    icon: mdi:battery-clock
    update_interval: never
    lambda: |-
        return {id(battery_last_replaced_global)};

text_sensor:
  - platform: template
    id: battery_type_text
    name: "Battery type"
    entity_category: diagnostic
    icon: mdi:battery-unknown
    update_interval: never
